Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lost_and_Found.Models;
using Microsoft.AspNetCore.Http;

namespace Lost_and_Found.Controllers
{
    public class AdminsController : Controller
    {
        private readonly AppDbContext _context;

        public AdminsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admins
        public async Task<IActionResult> Index()
        {
            return View(await _context.Admins.ToListAsync());
        }

        // GET: Admins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // GET: Admins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AdminId,FirstName,LastName,Email,Password,Address,Contact")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(admin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AdminId,FirstName,LastName,Email,Password,Address,Contact")] Admin admin)
        {
            if (id != admin.AdminId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.AdminId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admins
                .FirstOrDefaultAsync(m => m.AdminId == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var admin = await _context.Admins.FindAsync(id);
            _context.Admins.Remove(admin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //User Login
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Admin user)
        {

            var data = _context.Admins.Where(u => u.Email == user.Email && u.Password == user.Password).Count();
            if (data > 0)
            {


                HttpContext.Session.SetString("Admin", user.Email);
                return View("~/Views/Home/Index.cshtml");

            }
            else
            {

                return RedirectToAction(nameof(error));
            }


        }

        public ActionResult Logout(Admin user)
        {
            HttpContext.Session.Remove("Admin");
            return View("~/Views/Home/Index.cshtml");
        }

        public IActionResult error()
        {
            return View();
        }


        private bool AdminExists(int id)
        {
            return _context.Admins.Any(e => e.AdminId == id);
        }
    }
}

Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lost_and_Found.Models;
using Microsoft.AspNetCore.Http;
using RestSharp;

namespace Lost_and_Found.Controllers
{
    public class UsersController : Controller
    {
        private readonly AppDbContext _context;
      

        public UsersController(AppDbContext context)
        {
            _context = context;
        }


      
        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,FirstName,LastName,Email,Password,Address,Contact")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,FirstName,LastName,Email,Password,Address,Contact")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

      
        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }

        //User Login
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(User user)
        {

            var data = _context.Users.Where(u => u.Email == user.Email && u.Password == user.Password).Count();
                if (data > 0)
                {
                try
                {
                    var basu = _context.Users.FirstOrDefault(u => u.Email == user.Email);
                    HttpContext.Session.SetString("FirstName", basu.Email);
                    HttpContext.Session.SetInt32("UserId", basu.UserId);
              

                }
                catch (Exception ex)
                {
                    Console.WriteLine("An exception occurred: " + ex.Message);
                }

               
                // return View("~/Views/Home/Index.cshtml");
                return RedirectToAction(nameof(Success));


            }
                else
                {

                return RedirectToAction(nameof(error));
            }
            
        
        }

        public ActionResult Logout(User user)
        {
            HttpContext.Session.Remove("FirstName");
            HttpContext.Session.Remove("UserId");
            return View("~/Views/Home/Index.cshtml");
        }

        public IActionResult Success()
        {
            return View();
        }


        public IActionResult error()
        {
            return View();
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lost_and_Found</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Post"><img src="~/img/logo3.jpg" alt="site logo" class="site_logo" /></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active text-uppercase">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house"></i> Home</a>
                </li>


                @{

                    string admin = Context.Session.GetString("Admin");
                    string name = @Context.Session.GetString("FirstName");

                    if (name == null && admin == null)
                    {
                        <li class="nav-item text-uppercase">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Create"><i class="fa-solid fa-user-plus"></i> Register</a>
                        </li>

                        <li class="nav-item text-uppercase">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Login"><i class="fa-solid fa-user-check"></i> Login</a>
                        </li>

                    }
                    else if (name != null)
                    {
                        <li class="nav-item text-uppercase">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Logout"><i class="fa-solid fa-user"></i> Logout</a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item text-uppercase">
                            <a class="nav-link text-white" asp-area="" asp-controller="Admins" asp-action="Logout"><i class="fa-solid fa-user-minus"></i> Logout</a>
                        </li>
                    }
                }



                <li class="nav-item text-uppercase">
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Contact"><i class="fa-solid fa-phone"></i> Contact Us</a>
                </li>

                <li class="nav-item active text-uppercase">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Post"><i class="fa-solid fa-newspaper"></i> Recent Posts</a>
                </li>

                <li class="nav-item dropdown text-uppercase">
                    <a class="nav-link dropdown-toggle text-white" href="#" id="itemPostsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa-solid fa-clipboard-list"></i> All Posts
                    </a>
                    <div class="dropdown-menu" aria-labelledby="itemPostsDropdown">
                        <a class="dropdown-item" asp-area="" asp-controller="Lostitems" asp-action="Index">Lost Item Posts</a>
                        <a class="dropdown-item" asp-area="" asp-controller="Founditems" asp-action="Index">Found Item Posts</a>
                    </div>
                </li>

                @{
                    if (admin != null)
                    {

                        <li class="nav-item text-uppercase">
                            <a class="nav-link text-white" asp-area="" asp-controller="Users" asp-action="Index"><i class="fa-solid fa-user-minus"></i> Users</a>
                        </li>
                        
                        <li><span class="nav-link text-white">Hi!! @Context.Session.GetString("Admin")</span></li> 

                    }
                }


                @if (name != null)
                {
                    <li class="nav-item">
                        <span class="nav-link text-white">Hi!! @Context.Session.GetString("FirstName")</span>
                    </li>
                }

            </ul>

            <div class="form-inline my-2 my-lg-0">

                @using (Html.BeginForm("Search", "Home", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
                {
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="Search" required pattern=".*\S+.*" title="Please enter search phrase..." />
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Search</button>
                }

            </div>

        </div>
    </nav>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark text-center">
        <div class="container text-white p-2">
            &copy; 2023 - Lost and Found
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>